CC=gcc
CFLAGS=-Wall -std=c11

all: parametri1 parametri2 provaBUFSIZ contaOccorrenze mycat1 selezionaMultipli1 selezionaMultipli2 sostituisciCar sostituisciCar1 myhead1 myhead2 myhead3 selezionaLinea selezionaLunghezzaLinea padreFiglioConStatus padreSenzaFigli padreFiglioConStatus1 provaValoriWait

parametri1: parametri1.c
	$(CC) $(CFLAGS)	-o parametri1 parametri1.c

parametri2: parametri2.c
	$(CC) $(CFLAGS)	-o parametri2 parametri2.c

provaBUFSIZ: provaBUFSIZ.c
	$(CC) $(CFLAGS)	-o provaBUFSIZ provaBUFSIZ.c

contaOccorrenze: contaOccorrenze.c
	$(CC) $(CFLAGS)	-o contaOccorrenze contaOccorrenze.c

mycat1: mycat1.c
	$(CC) $(CFLAGS) -o mycat1 mycat1.c

selezionaMultipli1: selezionaMultipli1.c
	$(CC) $(CFLAGS) -o selezionaMultipli1 selezionaMultipli1.c

selezionaMultipli2: selezionaMultipli2.c
	$(CC) $(CFLAGS) -o selezionaMultipli2 selezionaMultipli2.c

sostituisciCar: sostituisciCar.c
	$(CC) $(CFLAGS) -o sostituisciCar sostituisciCar.c

sostituisciCar1: sostituisciCar1.c
	$(CC) $(CFLAGS) -o sostituisciCar1 sostituisciCar1.c

myhead1: myhead1.c
	$(CC) $(CFLAGS) -o myhead1 myhead1.c

myhead2: myhead2.c
	$(CC) $(CFLAGS) -o myhead2 myhead2.c

myhead3: myhead3.c
	$(CC) $(CFLAGS) -o myhead3 myhead3.c

selezionaLinea: selezionaLinea.c
	$(CC) $(CFLAGS) -o selezionaLinea selezionaLinea.c

selezionaLunghezzaLinea: selezionaLunghezzaLinea.c
	$(CC) $(CFLAGS) -o selezionaLunghezzaLinea selezionaLunghezzaLinea.c

padreFiglioConStatus: padreFiglioConStatus.c
	$(CC) $(CFLAGS) -o padreFiglioConStatus padreFiglioConStatus.c

padreSenzaFigli: padreSenzaFigli.c
	$(CC) $(CFLAGS) -o padreSenzaFigli padreSenzaFigli.c

padreFiglioConStatus1: padreFiglioConStatus1.c
	$(CC) $(CFLAGS) -o padreFiglioConStatus1 padreFiglioConStatus1.c

provaValoriWait: provaValoriWait.c
	$(CC) $(CFLAGS) -o provaValoriWait provaValoriWait.c
