CC = gcc
CFLAGS = -Wall -std=c11

all: 8Giu16 14Giu17 10Lug19

8Giu16: 8Giu16.c
	$(CC) $(CFLAGS) -o 8Giu16 8Giu16.c

14Giu17: 14Giu17.c
	$(CC) $(CFLAGS) -o 14Giu17 14Giu17.c

10Lug19: 10Lug19.c
	$(CC) $(CFLAGS) -o 10Lug19 10Lug19.c