CC = gcc
CFLAGS =-Wall -std=c11

all: 9Giu14 31Mag19 9Set16

9Giu14: 9Giu14.c
	$(CC) $(CFLAGS) -o 9Giu14 9Giu14.c

31Mag19: 31Mag19.c
	$(CC) $(CFLAGS) -o 31Mag19 31Mag19.c 

9Set16: 9Set16.c
	$(CC) $(CFLAGS) -o 9Set16 9Set16.c
