CC = gcc
CFLAGS = -Wall

all: 12Set18 9Set15 13Lug22

12Set18: 12Set18.c
	$(CC) $(CFLAGS) -o 12Set18 12Set18.c

9Set15: 9Set15.c
	$(CC) $(CFLAGS) -o 9Set15 9Set15.c

13Lug22: 13Lug22.c
	$(CC) $(CFLAGS) -o 13Lug22 13Lug22.c