CC=gcc
CFLAGS=-Wall -std=c11

all: padreFigliMultipli padreFigliConSalvataggioPID padreFigliConConteggioOccorrenze provaExec mylsConFork1 myGrepConFork-ridStError myGrepConFork-ridStErrorEInput myCatConFork mycat padreFigliNipotiConExec

padreFigliMultipli: padreFigliMultipli.c
	$(CC) $(CFLAGS) -o padreFigliMultipli padreFigliMultipli.c

padreFigliConSalvataggioPID: padreFigliConSalvataggioPID.c
	$(CC) $(CFLAGS) -o padreFigliConSalvataggioPID padreFigliConSalvataggioPID.c

padreFigliConConteggioOccorrenze: padreFigliConConteggioOccorrenze.c
	$(CC) $(CFLAGS) -o padreFigliConConteggioOccorrenze padreFigliConConteggioOccorrenze.c

provaExec: provaExec.c 
	$(CC) $(CFLAGS) -o provaExec provaExec.c

mylsConFork1: mylsConFork1.c
	$(CC) $(CFLAGS) -o mylsConFork1 mylsConFork1.c

myGrepConFork-ridStError: myGrepConFork-ridStError.c
	$(CC) $(CFLAGS) -o myGrepConFork-ridStError myGrepConFork-ridStError.c

myGrepConFork-ridStErrorEInput: myGrepConFork-ridStErrorEInput.c
	$(CC) $(CFLAGS) -o myGrepConFork-ridStErrorEInput myGrepConFork-ridStErrorEInput.c

myCatConFork: myCatConFork.c
	$(CC) $(CFLAGS) -o myCatConFork myCatConFork.c

mycat: mycat.c
	$(CC) $(CFLAGS) -o mycat mycat.c

padreFigliNipotiConExec: padreFigliNipotiConExec.c
	$(CC) $(CFLAGS) -o padreFigliNipotiConExec padreFigliNipotiConExec.c
