CC = gcc
CFLAGS=-Wall -std=c11

all: padreFigliMultipli padreFigliConSalvataggioPID

padreFigliMultipli: padreFigliMultipli.c
	$(CC) $(CFLAGS) -o padreFigliMultipli padreFigliMultipli.c

padreFigliConSalvataggioPID: padreFigliConSalvataggioPID.c
	$(CC) $(CFLAGS) -o padreFigliConSalvataggioPID padreFigliConSalvataggioPID.c
