CC = gcc
CFLAGS =-Wall -std=c11

all: 5Giu15Semplificato 5Giu15 12Feb16 12Lug17 11Lug18 17Feb21 19Gen22

5Giu15Semplificato: 5Giu15Semplificato.c
	$(CC) $(CFLAGS) -o 5Giu15Semplificato 5Giu15Semplificato.c

5Giu15: 5Giu15.c
	$(CC) $(CFLAGS) -o 5Giu15 5Giu15.c

12Feb16: 12Feb16.c
	$(CC) $(CFLAGS) -o 12Feb16 12Feb16.c

12Lug17: 12Lug17.c
	$(CC) $(CFLAGS) -o 12Lug17 12Lug17.c

11Lug18: 11Lug18.c
	$(CC) $(CFLAGS) -o 11Lug18 11Lug18.c

17Feb21: 17Feb21.c
	$(CC) $(CFLAGS) -o 17Feb21 17Feb21.c

19Gen22: 19Gen22.c
	$(CC) $(CFLAGS) -o 19Gen22 19Gen22.c