CC = gcc
CFLAGS =-Wall -std=c11

all: 5Giu15Semplificato 5Giu15 12Feb16 12Lug17

5Giu15Semplificato: 5Giu15Semplificato.c
	$(CC) $(CFLAGS) -o 5Giu15Semplificato 5Giu15Semplificato.c

5Giu15: 5Giu15.c
	$(CC) $(CFLAGS) -o 5Giu15 5Giu15.c

12Feb16: 12Feb16.c
	$(CC) $(CFLAGS) -o 12Feb16 12Feb16.c

12Lug17: 12Lug17.c
	$(CC) $(CFLAGS) -o 12Lug17 12Lug17.c