CC = gcc
CFLAGS =-Wall -std=c11

all: append1 creaPipe-bis provaPipe-SenzaClose provaPipe-Generico1 provaPipe-Generico2 provaEsame1 provaEsame2-a provaEsame2-b

append1: append1.c
	$(CC) $(CFLAGS) -o append1 append1.c

creaPipe-bis: creaPipe-bis.c
	$(CC) $(CFLAGS) -o creaPipe-bis creaPipe-bis.c

provaPipe-SenzaClose: provaPipe-SenzaClose.c
	$(CC) $(CFLAGS) -o provaPipe-SenzaClose provaPipe-SenzaClose.c

provaPipe-Generico1: provaPipe-Generico1.c
	gcc -Wall -std-c11 -o provaPipe-Generico1 provaPipe-Generico1.c

provaPipe-Generico2: provaPipe-Generico2.c
	$(CC) $(CFLAGS) -o provaPipe-Generico2 provaPipe-Generico2.c

provaEsame1: provaEsame1.c
	$(CC) $(CFLAGS) -o provaEsame1 provaEsame1.c

provaEsame2-a: provaEsame2-a.c
	$(CC) $(CFLAGS) -o provaEsame2-a provaEsame2-a.c

provaEsame2-b: provaEsame2-b.c
	$(CC) $(CFLAGS) -o provaEsame2-b provaEsame2-b.c
