CC = gcc
CFLAGS= -Wall -std=c11

all: append1 creaPipe-bis provaPipe-SenzaClose

append1: append1.c
	$(CC) $(CFLAGS) -o append1 append1.c

creaPipe-bis: creaPipe-bis.c
	$(CC) $(CFLAGS) -o creaPipe-bis creaPipe-bis.c

provaPipe-SenzaClose: provaPipe-SenzaClose.c
	$(CC) $(CFLAGS) -o provaPipe-SenzaClose provaPipe-SenzaClose.c
